export const CARD_STRINGS = {
  name: "Simple Irrigation",
  description: "Status and controls for a Simple Irrigation installation.",
  entity: "Schedule",
  entityHelp: "Choose the enabled switch for an individual irrigation schedule.",
  title: "Title",
  showDetails: "Show details",
  missingConfig: "Choose a Simple Irrigation entity in the card editor.",
  missingEntity: "The configured entity does not exist.",
  unavailable: "Simple Irrigation is unavailable",
  loading: "Loading irrigation entities…",
  noDevice: "Choose an individual Simple Irrigation schedule switch.",
  idle: "Idle",
  running: "Running",
  preparing: "Preparing",
  stopping: "Stopping",
  paused: "Paused",
  error: "Error",
  unknown: "Unknown",
  activeZones: "Active zones",
  nextRun: "Next run",
  mode: "Watering mode",
  schedule: "Schedule",
  enabled: "Enabled",
  disabled: "Disabled",
  run: "Run schedule",
  stop: "Stop",
  actionFailed: "The action could not be completed.",
} as const;
